"""ProblemConfig Pydantic model — central data contract for the optimization pipeline."""

from pydantic import BaseModel


class DecisionVariable(BaseModel):
    """A variable the optimizer controls."""

    name: str
    type: str  # "continuous" | "integer" | "binary"
    bounds: tuple[float, float] | None = None


class Objective(BaseModel):
    """What the optimizer is trying to achieve."""

    direction: str  # "minimize" | "maximize"
    description: str


class Constraint(BaseModel):
    """A constraint on the optimization problem."""

    name: str
    description: str
    type: str  # "hard" | "soft"
    parameters: dict


class UncertainParameter(BaseModel):
    """A parameter that must be predicted from data."""

    name: str
    description: str
    data_column: str


class ProblemConfig(BaseModel):
    """Complete specification of an optimization problem.

    Generated by the Intake Agent from user conversation.
    Consumed by Data Cleaning, Prediction, Optimizer, and Explanation modules.
    """

    problem_description: str
    decision_variables: list[DecisionVariable]
    objective: Objective
    constraints: list[Constraint]
    uncertain_parameters: list[UncertainParameter]
    cost_structure: dict
    data_requirements: dict
    solver_hint: str | None = None
