"""
problem_config.py
=================
Central data structure for the optimization agent pipeline.
Every module in the pipeline reads from this config.

Flow:
  User NL description
      -> Intake Module (LLM call #1) parses into ProblemConfig
      -> User reviews / edits in UI
      -> Data Module, Prediction Module, Optimizer, Explainer all consume this

Stakeholder modification = update one field here, re-run pipeline. That's it.
"""

from __future__ import annotations
from typing import Optional
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Sub-models
# ---------------------------------------------------------------------------

class DecisionVariable(BaseModel):
    """One thing the agent decides — e.g. order quantity for a specific item."""
    name: str = Field(..., description="e.g. 'order_qty_item_A'")
    type: str = Field("integer", description="continuous, integer, or binary")
    lower_bound: float = Field(0.0, description="Minimum allowed value")
    upper_bound: Optional[float] = Field(None, description="None = unbounded")
    unit: str = Field("units", description="e.g. 'units', 'dollars'")
    description: str = ""


class Objective(BaseModel):
    """What we are optimizing."""
    direction: str = Field("minimize", description="minimize or maximize")
    description: str = Field(
        ...,
        description="Plain English description of the objective"
    )
    metric_name: str = Field("total_cost", description="Key used in results dict")


class Constraint(BaseModel):
    """One business rule the optimizer must respect."""
    name: str
    description: str
    type: str = Field("hard", description="hard or soft")
    parameters: dict = Field(
        default_factory=dict,
        description="Numeric values. e.g. {'budget': 40000, 'currency': 'USD'}"
    )


class UncertainParameter(BaseModel):
    """Something we don't know at decision time — needs prediction from data."""
    name: str = Field(..., description="e.g. 'demand_item_A'")
    description: str
    data_column: str = Field(..., description="Column in cleaned data that measures this")
    unit: str = "units"


class CostItem(BaseModel):
    """One line in the cost structure."""
    name: str
    value: float
    unit: str = "USD/unit"
    description: str = ""
    period: Optional[int] = Field(
        None,
        description="If cost changes by period (e.g. product lifecycle year), specify here. None = all periods."
    )
    product_category: Optional[str] = Field(
        None,
        description="None = applies to all categories"
    )


class DataRequirements(BaseModel):
    """What columns the Data Module must find in the CSV."""
    required_columns: list[str] = Field(default_factory=list)
    target_column: str = "quantity"
    date_column: str = "order_date"
    train_years: list[int] = Field(default_factory=list)
    test_years: list[int] = Field(default_factory=list)
    groupby_keys: list[str] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Main ProblemConfig
# ---------------------------------------------------------------------------

class ProblemConfig(BaseModel):
    """
    The single source of truth for the entire pipeline.

    Generated by Intake Module (LLM call #1) from natural language.
    Validated by Pydantic before any downstream module touches it.
    Editable by user in the Config Review UI page.
    """

    # --- Identity ---
    problem_description: str = Field(
        ...,
        description="Original natural language input from the user"
    )
    problem_title: str = Field(
        "Optimization Problem",
        description="Short name shown in UI and reports"
    )

    # --- Core schema ---
    decision_variables: list[DecisionVariable] = Field(
        default_factory=list,
        description="What the agent controls"
    )
    objective: Objective = Field(
        default_factory=lambda: Objective(
            direction="minimize",
            description="Minimize total expected cost"
        )
    )
    constraints: list[Constraint] = Field(default_factory=list)
    uncertain_parameters: list[UncertainParameter] = Field(
        default_factory=list,
        description="Parameters that need prediction from data"
    )
    cost_structure: list[CostItem] = Field(
        default_factory=list,
        description="All cost components"
    )
    data_requirements: DataRequirements = Field(default_factory=DataRequirements)
    solver_hint: Optional[str] = Field(
        None,
        description="Problem class hint for the optimizer (e.g. 'newsvendor', 'LP', 'knapsack')"
    )

    # --- Domain-specific metadata (populated by the intake agent from data) ---
    item_categories: list[str] = Field(
        default_factory=list,
        description="Product categories found in the data (e.g. ['jersey', 'shorts', 'socks'])"
    )
    item_sizes: list[str] = Field(
        default_factory=list,
        description="Item sizes/variants found in the data"
    )
    time_periods: list[str] = Field(
        default_factory=list,
        description="Time periods in the data (e.g. seasons, months, quarters)"
    )
    custom_fields: dict = Field(
        default_factory=dict,
        description="Any additional domain-specific metadata"
    )


# ---------------------------------------------------------------------------
# Helpers used by downstream modules
# ---------------------------------------------------------------------------

def get_cost(config: ProblemConfig, category: str, cost_name: str,
             period: Optional[int] = None) -> float:
    """Look up a cost value from config.cost_structure.

    Falls back to category-agnostic cost if category-specific not found.

    Args:
        config: ProblemConfig with cost_structure.
        category: Product category to match.
        cost_name: Cost type name (e.g. 'overage_cost', 'unit_cost').
        period: Optional period number (e.g. lifecycle year).

    Returns:
        The cost value.
    """
    # Try exact match first (category + period)
    for item in config.cost_structure:
        if (item.name == cost_name
                and item.product_category == category
                and item.period == period):
            return item.value

    # Fall back to category match without period filter
    for item in config.cost_structure:
        if item.name == cost_name and item.product_category == category and item.period is None:
            return item.value

    # Fall back to any match on cost_name
    for item in config.cost_structure:
        if item.name == cost_name:
            return item.value

    # Try common aliases before giving up — intake may use different names
    _COST_ALIASES: dict[str, list[str]] = {
        "unit_cost": ["purchase_cost", "cost_per_unit", "base_cost"],
        "purchase_cost": ["unit_cost", "cost_per_unit", "base_cost"],
        "overage_cost": ["overstock_cost", "excess_cost", "surplus_cost"],
        "underage_cost": ["stockout_cost", "shortage_cost", "backorder_cost"],
    }
    for alias in _COST_ALIASES.get(cost_name, []):
        for item in config.cost_structure:
            if item.name == alias:
                return item.value

    raise KeyError(f"Cost '{cost_name}' not found for category='{category}', period={period}")


def get_budget(config: ProblemConfig) -> float:
    """Extract budget from constraints."""
    for c in config.constraints:
        if "budget" in c.name.lower():
            for key in ["budget_usd", "budget", "max_spend"]:
                if key in c.parameters:
                    return float(c.parameters[key])
    return float("inf")


def get_moq(config: ProblemConfig) -> int:
    """Extract minimum order quantity."""
    for c in config.constraints:
        if "minimum" in c.name.lower() or "moq" in c.name.lower():
            for key in ["moq_per_size", "moq", "min_qty", "minimum"]:
                if key in c.parameters:
                    return int(c.parameters[key])
    return 0
